import Head from "next/head";
import {
  ArrowRightIcon,
  Bars3Icon,
  CheckIcon,
  StarIcon,
} from "@heroicons/react/24/solid";
import { MouseParallax } from "react-just-parallax";
import { SocialIcon } from "react-social-icons";
import { motion, useAnimation } from "framer-motion";
import { useEffect, useState } from "react";
import Fade from "react-reveal/Fade";

export default function Home() {
  const [shouldShowAction, setShouldShowActions] = useState(true);
  const [lastYPos, setLastYPos] = useState(0);

  useEffect(() => {
    function handleScroll() {
      const yPos = window.scrollY;
      const isScrollingUp = yPos < lastYPos;
      setShouldShowActions(isScrollingUp);
      setLastYPos(yPos);
    }
    window.addEventListener("scroll", handleScroll, false);
    return () => {
      window.removeEventListener("scroll", handleScroll, false);
    };
  }, [lastYPos]);

  return (
    <div className="bg-black scroll-smooth ">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <motion.section
            className="sticky top-0 bg-black z-10"
            initial={{ opacity: 0 }}
            animate={{ opacity: shouldShowAction ? 1 : 0 }}
          >
            <div className="flex justify-between items-center p-4">
              <h1 className="text-white text-3xl md:text-4xl md:ml-5 lg:ml-10 font-semibold">
                bunq
              </h1>
              <div className="md:flex md:justify-center md:items-center gap-6">
                <p className="hidden md:inline-block text-white font-bold">
                  compare plans
                </p>
                <button className="hidden md:inline-block text-white bg-orange-500 hover:bg-orange-600 p-3 font-bold rounded-full">
                  Join us now
                </button>
                <button className="hidden md:inline-block bg-white rounded-full p-3 font-bold">
                  Log in
                </button>
                <Bars3Icon className="text-white h-10 md:mr-5 lg:mr-10" />
              </div>
            </div>
            <hr className="border-gray-700" />
          </motion.section>
          <section className="p-3 md:flex md:mt-5 lg:mt-0 md:justify-center  lg:justify-between lg:p-14 overflow-x-hidden 2xl:justify-evenly">
            <Fade left>
              <div className="md:p-8">
                <div className="mt-8 p-4 font-extrabold">
                  <p className="text-white text-4xl md:text-5xl lg:text-7xl">
                    back of
                    <br />
                    The Free
                  </p>
                </div>
                <div>
                  <p className="text-white text-2xl flex-grow md:text-2xl  font-medium ml-4 lg:text-3xl">
                    Mobile banking that Makes Life Easy.
                  </p>
                </div>
                <div>
                  <p className="text-white p-4 lg:text-xl">
                    Try now, no strings attached.
                  </p>
                  <div className="flex justify-center md:block p-4">
                    <button className="text-white flex-grow md:w-32 md:flex-grow-0 h-10 rounded-full bg-orange-500 hover:bg-orange-600">
                      Get Started
                    </button>
                  </div>
                </div>
              </div>
            </Fade>
            <Fade right>
              <div className="flex justify-center items-center md:block md:p-5">
                <img
                  className="h-[300px] md:h-96 md:w-96 lg:h-screen lg:w-full"
                  src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f5872ee6f83f33_Phone-card.webp"
                  alt=""
                />
              </div>
            </Fade>
          </section>
          <Fade left>
            <section className="flex justify-center flex-wrap gap-8 p-4 md:mt-7 lg:mt-0">
              <img
                className="h-16 w-16 md:h-32 md:w-32"
                src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f58747eef8411f_forbes-logo.svg"
                alt=""
              />
              <img
                className="h-16 w-16 md:h-32 md:w-32 "
                src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f58767a5f84120_thefintechtimes-logo.svg"
                alt=""
              />
              <img
                className="h-16 w-16  md:h-32 md:w-32"
                src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f5878418f8411a_reuters-logo.svg"
                alt=""
              />
              <img
                className="h-16 w-16 md:h-32 md:w-32 "
                src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f587e1f1f84118_techcrunch.svg"
                alt=""
              />
              <img
                className="h-16 w-16  md:h-32 md:w-32"
                src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f58724e9f84125_wired-logo.svg"
                alt=""
              />
              <img
                className="h-16 w-16 md:h-32 md:w-32 "
                src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f5877185f84123_business-insider-logo.svg"
                alt=""
              />
            </section>
          </Fade>
          <Fade left>
            <section className="p-4 mt-5">
              <div className="flex justify-center flex-col items-center">
                <p className="text-white font-bold text-4xl ">Our plans</p>
                <div className="mt-14 ">
                  <button className="bg-[#1c1c1c] text-[#767676] rounded-l-full p-4 focus:bg-[#4f4f4f] focus:text-white  font-bold">
                    Personal
                  </button>
                  <button className="bg-[#1c1c1c] text-[#767676] rounded-r-full p-4 focus:bg-[#4f4f4f] focus:text-white font-bold">
                    Business
                  </button>
                </div>
              </div>
              <div className="p-4 space-y-6 md:space-y-0 mt-10 md:flex md:justify-center md:space-x-8 md:items-center">
                <div className="flex gap-4 ">
                  <CheckIcon className=" h-9 text-blue-700 " />
                  <p className="text-white text-xl ">
                    Enjoy a 30-day free trial of any plan
                  </p>
                </div>
                <div className="flex gap-4">
                  <CheckIcon className=" h-9 text-blue-700" />
                  <p className="text-white text-xl ">
                    Switch or cancel your plan anytime
                  </p>
                </div>
              </div>
              <div className="m-2 flex flex-wrap gap-5 justify-center mt-10">
                <div className="h-96 w-72 bg-[#1c1c1c] rounded-[2.5rem] pt-10 p-8 flex flex-col  items-center">
                  <img
                    className="h-12"
                    src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/6284b4753c8fe3a7e452f5ed_Icon-Green-BG-Tree.svg"
                    alt=""
                  />
                  <h1 className="p-5 text-2xl font-bold text-white">
                    Easy Green
                  </h1>
                  <p className="text-white text-center ">
                    {" "}
                    Open your sustainable bank account to become CO2-free in
                    just 2 years with zero effort.
                  </p>
                  <p className="p-5  text-white">
                    <span className="font-bold">€17.99</span>/month
                  </p>
                  <button className="bg-white w-full h-full p-2 rounded-full font-bold">
                    Discover Easy Green
                  </button>
                </div>
                <div className="h-96 w-72 bg-[#1c1c1c] rounded-[2.5rem] pt-10 p-8 flex flex-col  items-center">
                  <img
                    className="h-12"
                    src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f5875c0bf8409a_easy-money.svg"
                    alt=""
                  />
                  <h1 className="p-5 text-2xl font-bold text-white">
                    Easy Money
                  </h1>
                  <p className="text-white text-center">
                    {" "}
                    Budget, save and bank like a local with multiple EU IBANs in
                    over 15 different currencies.
                  </p>
                  <p className="p-5  text-white">
                    <span className="font-bold">€8.99</span>/month
                  </p>
                  <button className="bg-white w-full h-full p-2 font-bold rounded-full">
                    Discover Easy Money
                  </button>
                </div>
                <div className="h-96 w-72 bg-[#1c1c1c] rounded-[2.5rem] pt-10 p-8 flex flex-col  items-center">
                  <img
                    className="h-12"
                    src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/62988ccfe9cc4c9e88c416a3_Icon-easy-bank.svg"
                    alt=""
                  />
                  <h1 className="p-5 text-2xl font-bold text-white">
                    Easy Bank
                  </h1>
                  <p className="text-white text-center">
                    {" "}
                    Get a bank account in just 5 minutes to save time and money
                    on instant payments.
                  </p>
                  <p className="p-5  text-white">
                    <span className="font-bold">€2.99</span>/month
                  </p>
                  <button className="bg-white w-full h-full p-2 rounded-full font-bold">
                    Discover Easy Bank
                  </button>
                </div>
                <div className="h-96 w-72 bg-[#1c1c1c] rounded-[2.5rem] pt-10 p-8 flex flex-col  items-center">
                  <img
                    className="h-12"
                    src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f5874537f83f89_EasySavingsIcon.svg"
                    alt=""
                  />
                  <h1 className="p-5 text-2xl font-bold text-white">
                    Easy Savings
                  </h1>
                  <p className="text-white text-center">
                    {" "}
                    The savings account with a kick! Sign up in 5 minutes to
                    earn high interest with zero fees.
                  </p>
                  <p className="p-5  text-white">
                    <span className="font-bold">Free</span>
                  </p>
                  <button className="bg-white w-full h-full p-2 rounded-full font-bold">
                    Discover Easy Savings
                  </button>
                </div>
              </div>
            </section>
          </Fade>
          <section className="p-5">
            <div className="flex justify-center ">
              <button className="font-bold flex-grow md:flex-grow-0 text-white border border-white p-3 rounded-full w-72">
                Compare plans
              </button>
            </div>
            <Fade left>
              <div className="mt-16 md:flex md:justify-center md:items-center md:gap-5 md:p-5 lg:p-10">
                <div className="max-w-[40rem]">
                  <p className="text-white font-extrabold text-3xl md:text-4xl lg:text-5xl">
                    We are{" "}
                    <span className="underline decoration-4 decoration-green-600">
                      bank of The Free
                    </span>
                  </p>
                  <p className="text-white mt-5  leading-7 text-lg ">
                    The future calls for banks that are sustainable in as many
                    ways as possible. We are the only bank in the world that
                    lets you choose how your money is invested. We are committed
                    to a green, inclusive and diverse future for anyone on the
                    planet.
                  </p>
                  <div className="flex justify-center lg:justify-start">
                    <button className="mt-5 bg-white text-black font-bold flex  justify-center items-center p-3 gap-4 rounded-full flex-grow md:flex-grow-0 ">
                      Learn more about us <ArrowRightIcon className="h-5" />
                    </button>
                  </div>
                </div>
                <div className="mt-5 md:mt-0">
                  <img
                    className="md:h-full hover:scale-105 transition ease-in-out duration-1000"
                    src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/63591409f1defd3921163231_Illustration-Globe-Phone.webp"
                    alt=""
                  />
                </div>
              </div>
            </Fade>
          </section>
          <Fade left>
            <section className="p-8 mt-5">
              <h1 className="text-white font-bold text-3xl text-center md:text-4xl lg:text-5xl">
                Sustainable, solid, secure.
              </h1>
              <div className="mt-16 space-y-10 md:flex md:justify-center md:items-center md:space-y-0  ">
                <div className="flex flex-col gap-5 md:max-w-[15rem] lg:max-w-none ">
                  <div>
                    <img
                      src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f587c56ff8405c_Shield.svg"
                      className="text-white h-14 w-14"
                      alt=""
                    />
                  </div>
                  <h1 className="text-white font-bold text-2xl lg:text-3xl">
                    Money Safety
                  </h1>
                  <p className="text-white font-medium md:pr-5 leading-relaxed">
                    We have our own banking permit granted by the ECB, your
                    money is secured up to €100.000.
                  </p>
                </div>
                <div className="flex flex-col gap-5 md:max-w-[15rem] lg:max-w-none">
                  <div>
                    <img
                      src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f587488cf83de2_Icon-Tree.svg"
                      className="h-14 w-14 text-white"
                      alt=""
                    />
                  </div>
                  <h1 className="text-white font-bold text-2xl lg:text-3xl">
                    Sustainable
                  </h1>
                  <p className="text-white font-medium md:pr-5  leading-relaxed">
                    We are the only bank in the world that lets you choose how
                    your money is invested.
                  </p>
                </div>
                <div className="flex flex-col gap-5 md:max-w-[15rem] lg:max-w-none">
                  <div>
                    <img
                      src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f5870723f83d35_Icon-Help.svg"
                      className="h-14 w-14 text-white"
                      alt=""
                    />
                  </div>
                  <h1 className="text-white font-bold text-2xl lg:text-3xl">
                    24/7 Online Support
                  </h1>
                  <p className="text-white font-medium leading-relaxed">
                    You can always reach out to us if you have any questions or
                    run into some problems. We speak your language.
                  </p>
                </div>
              </div>
            </section>
          </Fade>
          <Fade left>
            <section className="p-8 md:flex md:justify-center md:gap-10 lg:mt-20">
              <div className="relative">
                <div className="sticky top-24 left-0 right-0 lg:ml-20">
                  <div className="flex justify-center items-center ">
                    <h1 className="text-white text-4xl font-bold md:text-7xl max-w-sm text-center">
                      Don’t just <br /> take our word for it
                    </h1>
                  </div>
                  <div className="flex justify-center items-center mt-10 flex-col gap-5">
                    <div className="bg-[#1c1c1c] w-40 p-4 rounded-xl">
                      <div className="flex justify-center items-center">
                        <img
                          className="h-6"
                          src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/6373ad8755951f4695aa74a8_google-play-logo.svg"
                          alt=""
                        />
                      </div>
                      <div className="flex justify-center items-center">
                        <div className="flex gap-1   p-2">
                          <StarIcon className=" h-5 text-yellow-500" />
                          <StarIcon className=" h-5 text-yellow-500" />
                          <StarIcon className=" h-5 text-yellow-500" />
                          <StarIcon className=" h-5 text-yellow-500" />
                          <StarIcon className=" h-5 text-yellow-500" />
                        </div>
                      </div>
                      <div className="flex gap-1">
                        <span className="text-white after:border-r-2 after:ml-1 after:border-[#4f4f4f]">
                          4.2
                        </span>
                        <span className="text-white">19,346 Votes</span>
                      </div>
                    </div>
                    <div className="bg-[#1c1c1c] w-40 p-4 rounded-xl">
                      <div className="flex justify-center items-center">
                        <img
                          className="h-6"
                          src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/6373ad87584267c648051de4_app-store-logo.svg"
                          alt=""
                        />
                      </div>
                      <div className="flex justify-center items-center">
                        <div className="flex gap-1   p-2">
                          <StarIcon className=" h-5 text-yellow-500" />
                          <StarIcon className=" h-5 text-yellow-500" />
                          <StarIcon className=" h-5 text-yellow-500" />
                          <StarIcon className=" h-5 text-yellow-500" />
                          <StarIcon className=" h-5 text-yellow-500" />
                        </div>
                      </div>
                      <div className="flex gap-1">
                        <span className="text-white after:border-r-2 after:ml-1 after:border-[#4f4f4f]">
                          4.2
                        </span>
                        <span className="text-white">503 Votes</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="lg:flex lg:justify-center lg:items-center lg:gap-10 ">
                <div>
                  <div className="mt-10 md:mt-0 space-y-8 flex flex-col justify-center items-center ">
                    <div>
                      <div className="bg-[#1c1c1c] p-4 rounded-[3rem] space-y-4 md:max-w-[16rem]">
                        <div className="flex justify-between">
                          <div className="flex flex-col">
                            <div className="flex gap-1   p-2">
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                            </div>
                            <span className="text-white text-xs">
                              19 days ago
                            </span>
                          </div>
                          <img
                            src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/637663e3eccee8454b641065_trustpilot-logo.svg"
                            className="bg-[#2b2c2e] rounded-full p-2 h-14 w-14"
                            alt=""
                          />
                        </div>
                        <p className="text-white leading-7 text-sm">
                          They made banking online really simple and their card
                          options bring another level of savings and
                          convenience. I’ve been with bunq for two years now and
                          happy with the service.
                        </p>
                      </div>
                      <div className="ml-8 -mt-1">
                        <svg
                          width="32"
                          height="16"
                          viewBox="0 0 32 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M16 16.5L1.39876e-06 0.499997L32 0.5L16 16.5Z "
                            fill="#1C1C1C"
                          ></path>
                        </svg>
                      </div>
                    </div>
                    <div>
                      <div className="bg-[#1c1c1c] p-4 rounded-[3rem] space-y-4 md:max-w-[16rem]">
                        <div className="flex justify-between ">
                          <div className="flex flex-col">
                            <div className="flex gap-1   p-2">
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                            </div>
                            <span className="text-white text-xs">
                              25 days ago
                            </span>
                          </div>
                          <img
                            src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/637663e3eccee8454b641065_trustpilot-logo.svg"
                            className="bg-[#2b2c2e] rounded-full p-2 h-14 w-14"
                            alt=""
                          />
                        </div>
                        <p className="text-white leading-7 text-sm">
                          I haven’t encountered any problems since I started
                          using the app. Connecting my accounts was simple and
                          paying bills is a breeze.
                        </p>
                      </div>
                      <div className="ml-8 -mt-1">
                        <svg
                          width="32"
                          height="16"
                          viewBox="0 0 32 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M16 16.5L1.39876e-06 0.499997L32 0.5L16 16.5Z "
                            fill="#1C1C1C"
                          ></path>
                        </svg>
                      </div>
                    </div>
                    <div>
                      <div className="bg-[#1c1c1c] p-4 rounded-[3rem] space-y-4 md:max-w-[16rem]">
                        <div className="flex justify-between ">
                          <div className="flex flex-col">
                            <div className="flex gap-1   p-2">
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                            </div>
                            <span className="text-white text-xs">
                              2 months ago
                            </span>
                          </div>
                          <img
                            src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/63739e0871a33846fcb8b476_app-store-icon.svg"
                            className="bg-[#2b2c2e] rounded-full p-2 h-14 w-14"
                            alt=""
                          />
                        </div>
                        <p className="text-white leading-7 text-sm">
                          I have been using this bank for several years and I am
                          very happy with its services and functionalities
                        </p>
                      </div>
                      <div className="ml-8 -mt-1">
                        <svg
                          width="32"
                          height="16"
                          viewBox="0 0 32 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M16 16.5L1.39876e-06 0.499997L32 0.5L16 16.5Z "
                            fill="#1C1C1C"
                          ></path>
                        </svg>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="hidden lg:inline-block ">
                  <div className="mt-10 space-y-8">
                    <div>
                      <div className="bg-[#1c1c1c] p-4 rounded-[3rem] space-y-4 max-w-[16rem]">
                        <div className="flex justify-between ">
                          <div className="flex flex-col">
                            <div className="flex gap-1   p-2">
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                            </div>
                            <span className="text-white text-xs">
                              26 days ago
                            </span>
                          </div>
                          <img
                            src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/63739e09dabf3645dbebfe55_google-play-icon.svg"
                            className="bg-[#2b2c2e] rounded-full p-3 h-[50px] w-14"
                            alt=""
                          />
                        </div>
                        <p className="text-white leading-7 text-sm">
                          Debits are displayed within half an hour via mobile
                          phone notification. Simply wonderfully uncomplicated.
                          The best decision I could have made.
                        </p>
                      </div>
                      <div className="ml-8 -mt-1">
                        <svg
                          width="32"
                          height="16"
                          viewBox="0 0 32 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M16 16.5L1.39876e-06 0.499997L32 0.5L16 16.5Z "
                            fill="#1C1C1C"
                          ></path>
                        </svg>
                      </div>
                    </div>
                    <div>
                      <div className="bg-[#1c1c1c] p-4 rounded-[3rem] space-y-4 max-w-[16rem]">
                        <div className="flex justify-between ">
                          <div className="flex flex-col">
                            <div className="flex gap-1   p-2">
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                            </div>
                            <span className="text-white text-xs">
                              27 days ago
                            </span>
                          </div>
                          <img
                            src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/63739e09dabf3645dbebfe55_google-play-icon.svg"
                            className="bg-[#2b2c2e] rounded-full p-3 h-[50px] w-14"
                            alt=""
                          />
                        </div>
                        <p className="text-white leading-7 text-sm">
                          I love bunq and the app! Great features like creating
                          sub-accounts and linking them to your cards. Cards are
                          delivered quickly, you can create DigiCards in the
                          app. You can really tell that there is a motivated
                          team behind bunq who have fresh ideas. Keep it up!
                        </p>
                      </div>
                      <div className="ml-8 -mt-1">
                        <svg
                          width="32"
                          height="16"
                          viewBox="0 0 32 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M16 16.5L1.39876e-06 0.499997L32 0.5L16 16.5Z "
                            fill="#1C1C1C"
                          ></path>
                        </svg>
                      </div>
                    </div>
                    <div>
                      <div className="bg-[#1c1c1c] p-4 rounded-[3rem] space-y-4 max-w-[16rem]">
                        <div className="flex justify-between ">
                          <div className="flex flex-col">
                            <div className="flex gap-1   p-2">
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                            </div>
                            <span className="text-white text-xs">
                              27 days ago
                            </span>
                          </div>
                          <img
                            src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/637663e3eccee8454b641065_trustpilot-logo.svg"
                            className="bg-[#2b2c2e] rounded-full p-2 h-14 w-14"
                            alt=""
                          />
                        </div>
                        <p className="text-white leading-7 text-sm">
                          In my opinion, there`s no other account with so many
                          innovative functions! Think about using bunq as a
                          salary account in the near future.
                        </p>
                      </div>
                      <div className="ml-8 -mt-1">
                        <svg
                          width="32"
                          height="16"
                          viewBox="0 0 32 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M16 16.5L1.39876e-06 0.499997L32 0.5L16 16.5Z "
                            fill="#1C1C1C"
                          ></path>
                        </svg>
                      </div>
                    </div>
                    <div>
                      <div className="bg-[#1c1c1c] p-4 rounded-[3rem] space-y-4 max-w-[16rem]">
                        <div className="flex justify-between ">
                          <div className="flex flex-col">
                            <div className="flex gap-1   p-2">
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                              <StarIcon className=" h-4 text-yellow-500" />
                            </div>
                            <span className="text-white text-xs">
                              28 days ago
                            </span>
                          </div>
                          <img
                            src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/63739e0871a33846fcb8b476_app-store-icon.svg"
                            className="bg-[#2b2c2e] rounded-full p-2 h-14 w-14"
                            alt=""
                          />
                        </div>
                        <p className="text-white leading-7 text-sm">Superb</p>
                      </div>
                      <div className="ml-8 -mt-1">
                        <svg
                          width="32"
                          height="16"
                          viewBox="0 0 32 16"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M16 16.5L1.39876e-06 0.499997L32 0.5L16 16.5Z "
                            fill="#1C1C1C"
                          ></path>
                        </svg>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </section>
          </Fade>
          <Fade left>
            <section className="p-5 flex justify-center items-center flex-col gap-5">
              <h1 className="text-white text-3xl font-bold text-center">
                Start your 30-day free trial
              </h1>
              <p className="text-white leading-relaxed text-center">
                Open your account in just 5 minutes, directly from your
                smartphone.
              </p>
              <button className="text-white bg-orange-500 hover:bg-orange-600  p-3 rounded-full font-bold">
                Get Started
              </button>
              <div>
                <MouseParallax
                  enableOnTouchDevice
                  strength={0.08}
                  lerpEase={0.04}
                  shouldResetPosition
                >
                  <img
                    className="w-full max-w-3xl -rotate-3"
                    src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f58768a8f840ae_rainbow-phone.png"
                    alt=""
                  />
                </MouseParallax>
              </div>
            </section>
          </Fade>
        </main>
        <footer className="bg-[#1c1c1c] ">
          <div className=" p-5 mt-10 md:flex md:justify-around md:flex-wrap lg:p-5 md:mt-5">
            <div className="flex flex-col gap-5 pt-10 justify-center md:justify-between items-center">
              <h1 className="text-white text-3xl font-bold">bunq</h1>
              <button className="bg-white p-3 rounded-full font-bold tracking-widest">
                English
              </button>
            </div>
            <div className="mt-10 space-y-4">
              <p className="font-bold text-white">Company</p>
              <p className="font-bold text-[#898989]">Mortgages</p>
              <p className="font-bold text-[#898989]">About us</p>
              <p className="font-bold text-[#898989]">Jobs</p>
              <p className="font-bold text-[#898989]">Blogs</p>
              <p className="font-bold text-[#898989]">Press</p>
            </div>
            <div className="mt-10 space-y-4">
              <p className="font-bold text-white">Help</p>
              <p className="font-bold text-[#898989]">Help Desk</p>
              <p className="font-bold text-[#898989]">Our Policies</p>
              <p className="font-bold text-[#898989]">Terms & Conditions</p>
              <p className="font-bold text-[#898989]">Developer</p>
            </div>
            <div className="md:flex md:flex-col md:justify-between space-y-5">
              <div className="flex justify-center items-center mt-10">
                <SocialIcon
                  bgColor="transparent"
                  fgColor="white"
                  network="instagram"
                />
                <SocialIcon
                  bgColor="transparent"
                  fgColor="white"
                  network="twitter"
                />
                <SocialIcon
                  bgColor="transparent"
                  fgColor="white"
                  network="linkedin"
                />
                <SocialIcon
                  bgColor="transparent"
                  fgColor="white"
                  network="facebook"
                />
              </div>

              <div className="flex justify-evenly">
                <img
                  className="w-32"
                  src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f5875524f840aa_App%20Store%20-%20EN.svg"
                  alt=""
                />
                <img
                  className="w-36"
                  src="https://assets-global.website-files.com/626045a016f5876d0cf83a9f/626045a016f58721d9f840a2_Google%20Play%20-%20EN.svg"
                  alt=""
                />
              </div>
            </div>
          </div>
          <div className="p-5">
            <div className="border-b mt-10 border-[#898989]" />
            <div className="flex flex-col justify-center items-center mt-10 space-y-5 md:flex-row md:justify-between md:space-y-0">
              <h1 className="text-[#898989] text-lg">© 2022 bunq</h1>
              <div className="flex gap-5 ">
                <p className="underline text-[#898989]">Privacy</p>
                <p className="underline text-[#898989]">Pricing</p>
                <p className="underline text-[#898989]">Site Map</p>
              </div>
            </div>
          </div>
        </footer>
      </div>
  );
}
